export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCESS: "LOGIN_SUCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCESS: "LOGOUT_SUCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    FORGET_REQUEST: "FORGET_REQUEST",
    FORGET_SUCESS: "FORGET_SUCESS",
    FORGET_FAILURE: "FORGET_FAILURE",
    RESET_REQUEST: "RESET_REQUEST",
    RESET_SUCESS: "RESET_SUCESS",
    RESET_FAILURE: "RESET_FAILURE",
    LOGIN_VIA_GOOGLE_REQUEST: "LOGIN_VIA_GOOGLE_REQUEST",
    LOGIN_VIA_GOOGLE_SUCESS: "LOGIN_VIA_GOOGLE_SUCESS",
    LOGIN_VIA_GOOGLE_FAILURE: "LOGIN_VIA_GOOGLE_FAILURE",
  };
  
export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCESS: "USER_REGISTER_SUCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
  };